version: '3.8'

services:
  # Neon Local proxy service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    environment:
      DELETE_BRANCH: true # Ephemeral branches for development
    # volumes:
    # Optional: For persistent branches per git branch
    # - ./.neon_local/:/tmp/.neon_local
    # - ./.git/HEAD:/tmp/.git/HEAD:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -U neon']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - acquisitions-network

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development

    depends_on:
      neon-local:
        condition: service_healthy
    volumes:
      # Mount source code for development (optional - for hot reload)
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
    restart: unless-stopped
    networks:
      - acquisitions-network

  # Optional: Add a development database management tool
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: acquisitions-pgadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dev@acquisitions.local
  #     PGADMIN_DEFAULT_PASSWORD: devpassword
  #   depends_on:
  #     - neon-local
  #   networks:
  #     - acquisitions-network

networks:
  acquisitions-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  neon_local_data:
    driver: local
